### ISSUE TITLE
Getting error while importing the sql file. 

### ISSUE THREAD

**Issue by Libbna** [RChaubey16/Blogging-Website#34]
![image](https://user-images.githubusercontent.com/46792570/132118074-ef524b81-f948-4686-90d8-cc03d4f03815.png)

**Comment by RChaubey16** [comment]
This issue has been fixed.

**Comment by vbadkar** [comment]
This issue is also observed on my side and its still occurring.
![image](https://user-images.githubusercontent.com/87715018/132304309-02cc4dc2-a1e0-4be6-82d8-067a995ead67.png)

**Comment by vbadkar** [comment]
![image](https://user-images.githubusercontent.com/87715018/132309194-fa41de0f-61c9-4456-8ca4-9dad606faea4.png)
This issue has been resolved

**Comment by Libbna** [comment]
![image](https://user-images.githubusercontent.com/46792570/133480375-0d03b533-f729-4fd3-91ec-38e8e3a24679.png)
@vbadkar yes you can close the issue now. 
The issue has been resolved on my side too.

**Comment by Libbna** [comment]
I was importing the file again because you made changes in it. Before it did import successfully but now facing the same issue.

**Comment by Libbna** [comment]
The issue is resolved.
After removing collation utf8mb4_0900_ai_ci from all the tables, it was successfully imported into the database.
